#' upload_txt
#' 
#' @description Imports and saves raw data generated by the N2a assay stored in `.txt` files (96-well plate layout).
#' 
#' @return A list of imported datasets saved in the global environment.
#' 
#' @examples
#' upload_txt()
#' 
#' @export


upload_txt <- function() {
  cat("Please select the TXT file.\n")
  filename <- file.choose()
  cat("Importing data from:", filename, "\n")
  
  datasets <- unlist(strsplit(paste(readLines(filename), collapse = "\n"), "\n\n"))
  data_list <- lapply(seq_along(datasets), function(i) {
    df <- tryCatch({
      temp_df <- read.table(text = datasets[i], header = FALSE, stringsAsFactors = FALSE, sep = "")
      temp_df[] <- lapply(temp_df, function(x) as.numeric(gsub(",", ".", x)))
      return(temp_df)
    }, error = function(e) {
      message("Error reading dataset:", i)
      return(NULL)
    })
    return(df)
  })
  
  names(data_list) <- paste0("dataset_", seq_along(datasets))
  cat("Data imported and stored.\n")
  return(data_list)
}

