#' upload_txt
#' 
#' @description Imports and saves raw data generated by the N2a assay stored in `.txt` files (96-well plate layout).
#' 
#' @return A list of imported datasets saved in the global environment.
#' 
#' @examples
#' upload_txt()
#' 
#' @export


upload_txt <- function() {
  cat("Please select the TXT file.\n")
  filename <- file.choose()
  
  if (tolower(tools::file_ext(filename)) != "txt") {
    stop("Unvalid filetype, please select .txt-based file. Import aborted.")
  }
  
  raw_text <- suppressWarnings(readLines(filename, warn = FALSE)) 
  
  datasets <- unlist(strsplit(paste(raw_text, collapse = "\n"), "\n\n"))
  
  data_list <- lapply(seq_along(datasets), function(i) {
    df <- tryCatch({
      temp_df <- suppressWarnings(read.table(text = datasets[i], header = FALSE, stringsAsFactors = FALSE, sep = ""))  
      
      temp_df[] <- lapply(temp_df, function(x) {
        x <- gsub(",", ".", x)  
        if (any(is.na(suppressWarnings(as.numeric(x))))) {  
          stop("Non-numeric character(s) detected. Import aborted.")
        }
        return(as.numeric(x))
      })
      
      if (nrow(temp_df) != 8 || ncol(temp_df) != 12) {
        stop("Datasets outside expected dimensions (8x12), check if datasets are separated by double line breaks. Import aborted.")
      }
      
      return(temp_df)
    }, error = function(e) {
      stop(e$message)  
    })
    return(df)
  })
  
  names(data_list) <- paste0("dataset_", seq_along(datasets))
  return(data_list)
}



